### ISSUE TITLE
webpack5 and svelte4 build error

### ISSUE THREAD

**Issue by lelouch-xue** [Ameobea/homepage#45]
I have read your article, [https://cprimozic.net/notes/posts/fixing-cant-resolve-svelte-internal-disclose-version-error](https://cprimozic.net/notes/posts/fixing-cant-resolve-svelte-internal-disclose-version-error/) After packaging, I still have different issues. **Uncaught Error: ES Modules may not assign module. exports or exports. *, Use ESM export syntax, installed: 4451**. I would like to take a look at your example project. Thank you very much!!!

**Comment by Ameobea** [comment]
Hi,

I'm afraid I don't know what's causing your particular issue.  It might be an issue with one of your dependencies, or with some file in your project itself.

Here is the Sveltekit project I was working on when I wrote that blog post: https://github.com/Ameobea/sketches-3d

I wish you luck figuring out your problem!

**Comment by lelouch-xue** [comment]
thank you!
